// Just for fun 😎

export const emojis = {
  fleche_droite: '➡️',
  fleche_gauche: '⬅️',
  fleche_haut: '⬆️',
  fleche_bas: '⬇️',
  fleche_horizontale: '↔️',
  fleche_haut_droite: '↗️',
  fleche_haut_gauche: '↖️',
  fleche_bas_droite: '↘️',
  fleche_bas_gauche: '↙️',
  cercle_blanc: '⚪',
  carre_blanc: '⬜',
  cercle_noir: '⚫',
  carre_noir: '⬛',
  cercle_rouge: '🔴',
  cercle_bleu: '🔵',
  croix: '❌',
  check: '✅',
  point_interrogation: '❓',
  point_exclamation: '❗',
  warning: '⚠️',
  info: 'ℹ️',
  bouton: '🔘',
  lumiere: '💡',
  visage_souriant: '😀',
  visage_souriant_yeux_rieurs: '😃',
  visage_sourire_large: '😁',
  visage_lunettes_de_soleil: '😎',
  visage_de_fete: '🥳',
  boite: '📦',
  poubelle: '🗑️',
  epingle: '📍',
  ballon: '🎈',
  etiquette: '🏷️',
  cle: '🔑',
  cle_ancienne: '🗝️',
  main_levee: '✋',
  salut: '👋',
  main_dos_tourne: '🤚',
  ok: '👌',
  pouce_en_lair: '👍',
  fleche_tournante: '🔄',
  fusee: '🚀',
  drapeau_a_damier: '🏁',
  boussole: '🧭',
  globe_terrestre: '🌍',
  carte: '🗺️',
  cible: '🎯',
  engrenage: '⚙️',
  chaine: '🔗',
  graphique: '📊',
};

export type Emoji = keyof typeof emojis;
